# Generated by Django 4.1 on 2022-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('symbol', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('percent_change_24h', models.IntegerField()),
                ('percent_change_7d', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('volume_24h', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
            ],
        ),
    ]
