# Generated by Django 4.1 on 2023-04-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('symbol', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap', models.IntegerField()),
                ('volume_24h', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreciousMetalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
