# Generated by Django 4.1 on 2023-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('author', models.TextField(max_length=100)),
                ('published', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
