# Generated by Django 4.1 on 2023-01-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0002_rename_crypto_cryptomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptomodel',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptomodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
